// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SelectTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void selectTest() {
    driver.get("https://www.baidu.com/?tn=75144485_dg&ch=4&ie=utf-8");
    driver.manage().window().setSize(new Dimension(1552, 976));
    driver.findElement(By.id("head")).click();
    driver.findElement(By.cssSelector("html")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".guide-bub-container_2skZT"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("chat-textarea")).click();
    driver.findElement(By.id("chat-textarea")).sendKeys("selenium");
    {
      WebElement element = driver.findElement(By.cssSelector(".cosd-search-header-brand-area"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
  }
}
