// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class StudentManagerTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void studentManager() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(790, 960));
    driver.findElement(By.id("submitBtn")).click();
    {
      WebElement element = driver.findElement(By.id("submitBtn"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".l-btn-text")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("admin");
    driver.findElement(By.id("submitBtn")).click();
    {
      WebElement element = driver.findElement(By.id("submitBtn"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".messager-button")).click();
    driver.findElement(By.cssSelector(".l-btn-text")).click();
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("12345");
    driver.findElement(By.name("code")).click();
    driver.findElement(By.name("code")).sendKeys("55Lt");
    driver.findElement(By.id("submitBtn")).click();
    driver.findElement(By.linkText("Ok")).click();
    driver.findElement(By.cssSelector(".hover > ins")).click();
    driver.findElement(By.name("code")).click();
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("123456");
    driver.findElement(By.name("code")).click();
    driver.findElement(By.name("code")).sendKeys("1234");
    driver.findElement(By.id("submitBtn")).click();
    driver.findElement(By.cssSelector(".messager-body")).click();
    driver.findElement(By.linkText("Ok")).click();
    driver.findElement(By.name("code")).click();
    driver.findElement(By.name("code")).sendKeys("AHDE");
    driver.findElement(By.cssSelector(".row:nth-child(5)")).click();
    driver.findElement(By.id("submitBtn")).click();
    driver.findElement(By.linkText("Ok")).click();
    driver.findElement(By.name("code")).click();
    driver.findElement(By.name("code")).sendKeys("bUQT");
    driver.findElement(By.id("submitBtn")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("admin");
    driver.findElement(By.id("form")).click();
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("123456");
    driver.findElement(By.name("code")).click();
    driver.findElement(By.name("code")).sendKeys("H88L");
    driver.findElement(By.cssSelector(".hover > ins")).click();
    driver.findElement(By.id("submitBtn")).click();
    driver.findElement(By.cssSelector(".panel:nth-child(9) .panel-title")).click();
    driver.findElement(By.cssSelector(".head")).click();
    driver.findElement(By.id("loginOut")).click();
  }
}
